---
###########################
# Ansible Playbook: WebNode
# Source Repository: https://github.com/build-boxes/webnode
###########################
- name: Playbook Create WebNode 
  hosts: all
  vars_files:
    - ./vars/vars.yml
    - ./vars/secrets.yml
  become: true

  # For Playbook - OS Specifc Vars.
  pre_tasks:
    - debug: var=ansible_os_family
    - name: Load OS specific Vars file for playbook, if any.
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - "./vars/os_specific_{{ ansible_os_family }}.yml"
        - "./vars/os_specific_default.yml"
    - name: Load OS specific Secret Vars file for playbook, if any.
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - "./vars/vsecrets_{{ ansible_os_family }}.yml"
        - "./vars/vsecrets_default.yml"
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
      when:
        - ansible_os_family == 'Debian'  
    - name: Update and upgrade yum packages
      become: true
      yum:
        update_cache: yes
        name: '*'
        state: latest
      when:
        - ansible_os_family == 'RedHat'              

  roles:
    - role: hammadrauf.sudousers
    - role: fauust.mariadb
    - role: hammadrauf.apache2

