---
###########################
# Ansible Playbook: WebNode- main.yml
#   Creates WebNode by orchestrating diffrent roles and tasks.
# Source Repository: https://github.com/build-boxes/webnode
###########################
- name: Playbook Create WebNode - main.yml
  hosts: all
  vars_files:
    - ./vars/vars.yml
    - ./vars/secrets.yml
  #become: true

  # For Playbook - OS Specifc Vars.
  pre_tasks:
    - debug: var=ansible_env.LOGNAME
    - debug: var=ansible_os_family
    - name: Load OS specific Vars file for playbook, if any.
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - "./vars/os_specific_{{ ansible_os_family }}.yml"
        - "./vars/os_specific_default.yml"
    - name: Load OS specific Secret Vars file for playbook, if any.
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - "./vars/vsecrets_{{ ansible_os_family }}.yml"
        - "./vars/vsecrets_default.yml"
    - name: Ensure Ansible tmp directory exists with correct permissions for "sudo su unprevilged"
      become: true
      ansible.builtin.file:
        path: "/root/.ansible/tmp"
        state: directory
        mode: '1777'
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
      when:
        - ansible_os_family == 'Debian'  
    - name: Perform a Block of RHEL Family pre-tasks
      become: true
      block:
        - name: Update and upgrade yum packages
          yum:
            update_cache: yes
            name: '*'
            state: latest
        - name: Perform repo-epel role tasks
          include_role:
            name: geerlingguy.repo-epel
        - name: Perform repo-remi role tasks
          include_role:
            name: geerlingguy.repo-remi
        - name: Update yum/dnf configuration 
          shell: |
            dnf config-manager --set-enabled epel
            dnf config-manager --set-enabled remi
      when:
        - ansible_os_family == 'RedHat'  
  # roles:
  #   - role: hammadrauf.sudousers
  #   - role: fauust.mariadb
  #   - role: hammadrauf.apache2
  #   - role: geerlingguy.php

  tasks:
    - name: Block to include roles as user root
      block:
        - name: Perform Sudouser role tasks
          include_role:
            name: hammadrauf.sudousers

        - name: Ensure Ansible tmp directory exists with correct permissions for "sudo su unprevilged"
          ansible.builtin.file:
            path: "/home/{{ su_vault_vmuser1 }}/.ansible/tmp"
            state: directory
            mode: '1777'
            owner: "{{ su_vault_vmuser1 }}"
            group: "{{ su_vault_vmuser1 }}"

        - name: Perform mariadb role tasks
          include_role:
            name: fauust.mariadb

        - name: Perform Apache/Httpd role tasks
          include_role:
            name: hammadrauf.apache2

        - name: Perform PHP role tasks
          include_role:
            name: geerlingguy.php

        - name: Perform CertBot role tasks
          include_role:
            name: geerlingguy.certbot            
      become: true

    - name: Adding groups to su_users list
      become: true
      user: 
        name: "{{ item.username }}"
        groups:
          - "{{ mariadb_user }}"
          - "{{ ap2_vapache_group }}"
        append: yes
      with_items:
        - "{{ su_users }}"    

    - name: Fix php-fpm on RHEL like servers
      become: true
      block:
        - name: Fix php-fpm run file, remove wrong line 1
          lineinfile:
            path: /etc/php-fpm.d/www.conf
            state: absent
            regexp: "^listen = .*"
        - name: Fix php-fpm run file, remove wrong line 2
          lineinfile:
            path: /etc/php-fpm.d/www.conf
            state: absent
            regexp: "^listen.allowed.*"
        - name: Fix php-fpm run file, insert correct line
          lineinfile:
            path: /etc/php-fpm.d/www.conf
            state: present
            insertafter: "^[www]\n"
            line: "listen = /run/php-fpm/www.sock"
      when:
        - ansible_os_family == 'RedHat'

    - name: Include Wordpress tasks
      include_tasks: wordpress.yml