---
- name: Play - Create 2 Super Users 
  hosts: all
  vars_files:
    - ./vars/vars.yml
    - ./vars/secrets.yml
  become: true

  tasks:
    - name: Create Super User 1
      user:
        name: "{{ vmuser1 }}"
        password: "{{ vmpwd1 }}"
        create_home: true
        groups: sudo,mail,users
        shell: /bin/bash
        expires: -1

    - name: Create .ssh folder for Super User 1
      file:
        path: "/home/{{ vmuser1 }}/.ssh"
        state: directory

    - name: Append user Public key to Authorized_keys for Super User 1
      shell: "cat /home/vagrant/.ssh/me.pub >> /home/{{ vmuser1 }}/.ssh/authorized_keys"
      args:
        creates: "/home/{{ vmuser1 }}/.ssh/authorized_keys"

    - name: Add NOPASSWD Sudo into SUDOERS for Super User 1
      lineinfile:
        path: /etc/sudoers
        line: "{{ vmuser1 }}        ALL=(ALL)       NOPASSWD: ALL"
        validate: /usr/sbin/visudo -cf %s

    - name: Set Home directory ownership - Super User 1
      file:
        path: "/home/{{ vmuser1 }}"
        owner: "{{ vmuser1 }}"
        group: "{{ vmuser1 }}"
        recurse: true

    - name: Create Super User 2
      user:
        name: "{{ vmuser2 }}"
        password: "{{ vmpwd2 }}"
        create_home: true
        groups: sudo,mail,users
        shell: /bin/bash
        expires: -1

    - name: Create .ssh folder for Super User 2
      file:
        path: "/home/{{ vmuser2 }}/.ssh"
        state: directory

    - name: Append user Public key to Authorized_keys for Super User 2
      shell: "cat /home/vagrant/.ssh/me.pub >> /home/{{ vmuser2 }}/.ssh/authorized_keys"
      args:
        creates: "/home/{{ vmuser2 }}/.ssh/authorized_keys"

    - name: Add NOPASSWD Sudo into SUDOERS for Super User 2
      lineinfile:
        path: /etc/sudoers
        line: "{{ vmuser2 }}        ALL=(ALL)       NOPASSWD: ALL"
        validate: /usr/sbin/visudo -cf %s

    - name: Set Home directory ownership - Super User 2
      file:
        path: "/home/{{ vmuser2 }}"
        owner: "{{ vmuser2 }}"
        group: "{{ vmuser2 }}"
        recurse: true

- name: Play - Install Apache
  hosts: all
  vars_files:
    - ./vars/vars.yml
    - ./vars/secrets.yml
  remote_user: "{{ vmuser1 }}"

  pre_tasks:
    - debug: var=ansible_os_family
    - name: Load OS specific Vars file
      include_vars: "{{ item }}"
      with_first_found:
        - "./vars/os_specific_{{ ansible_os_family }}.yml"
        - "./vars/os_specific_default.yml"

  tasks:
    - name: Install package Apache
      package:
        name: "{{ vapache }}"
        state: present
      become: true

